apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: s3-secret
  namespace: kubeflow
spec:
  provider: aws
  secretObjects:
    - secretName: mlpipeline-minio-artifact
      type: Opaque
      data:
        - objectName: "access"
          key: accesskey
        - objectName: "secret"
          key: secretkey
  parameters:
    objects: "- objectName: \"/parameter/region/infra/deploy/s3\"\n  objectType: \"secretsmanager\"\n  jmesPath:\n      - path: \"accesskey\"\n        objectAlias: \"access\"\n      - path: \"secretkey\"\n        objectAlias: \"secret\"           \n"
