apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeflow-pipelines-profile-controller
spec:
  template:
    spec:
      containers:
      - name: profile-controller
        env:
        - name: MINIO_SERVICE_REGION
          valueFrom:
            configMapKeyRef:
              optional: true
              name: pipeline-install-config
              key: minioServiceRegion
