apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../upstream/common/dex/overlays/istio
patches:
  - path: add-node-selector.yaml
    target:
      kind: Deployment
  - path: config-map.yaml
