apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: not-important
spec:
  template:
    spec:
      containers:
      - name: authservice
        volumeMounts:
          - name: data
            mountPath: /var/lib/authservice
      # Add Node Selector
      nodeSelector:
        aic-role: controller
