apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../upstream/contrib/kserve/models-web-app/overlays/kubeflow
patches:
  - path: add-node-selector.yaml
    target:
      kind: Deployment
