apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../upstream/common/cert-manager/cert-manager/base
patches:
  - path: add-node-selector.yaml
    target:
      kind: Deployment
